### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by haesleinhuepf** [brisvag/napari-help#1]
Hi Lorenzo @brisvag ,

just a quick question (no pressure): Could you imagine publishing this plugin under a more permissive license? It seems very useful, especially for beginners. I would love to make it part of my plugin collection devbio-napari, but GPL is an incompatible license unfortunately. BSD, MIT, Apache, etc would work.

Thanks for considering!

Best,
Robert

**Comment by brisvag** [comment]
[GPL is not incompatible with your meta-plugin use case](https://www.gnu.org/licenses/gpl-faq.html#GPLInProprietarySystem), since the rest of the plugins work just fine without it and 
viceversa. So feel free to add it to the collection :)

EDIT: you just need to make it clear that it's GPL and add a copy of the license, and you're good to go.

**Comment by haesleinhuepf** [comment]
Ok, thanks @brisvag . Our lawyers here see that differently ☺️
